project:
  type: book

bibliography: dxi-skript.bib

lang: de
# Change labels that are not properly changed by the language
crossref:
  eq-prefix: Formel # (default is "Equation")
  prp-title: Satz

book:
  title: Einführung in die Datenwissenschaft mit Excel
  author: 
  - name: Christian Glahn  
  page-navigation: true

  chapters:
  - index.qmd
  # - vorwort.qmd
 
  # Woche 1
  - part: Ausgangslage und Vorbereitung
    chapters:
    - kapitel/einleitung/kapitel.md
    - kapitel/einleitung/excel-versionen.md
  
  - part: "Datenquellen"
    chapters:
    # Woche 2
    - kapitel/daten-sammeln/kapitel.md
    # Woche 3
    - kapitel/daten-organisieren/kapitel.md

    # Woche 4
    - kapitel/datentypen/kapitel.md

    # Woche 5
    - kapitel/daten-importieren/kapitel.md

  - part: "Mathematik der Daten"
    chapters:
    # Woche 6
    - kapitel/variablen/kapitel.md
    # Woche ?
    - kapitel/zeichenketten/kapitel.md
    # Woche 8
    - kapitel/boolsche-operationen/kapitel.md
    # Woche 9
    - kapitel/vektor-operationen/kapitel.md
    # Woche 10 
    - kapitel/matrix-operationen/kapitel.md
  
    # Woche 11 
    - kapitel/kodieren-gruppieren/kapitel.md
    - kapitel/daten-formen/kapitel.md

  - part: "Deskriptive Datenanalyse"
    chapters:
    # Woche 14
    - kapitel/daten-beschreiben/kapitel.md
    # Woche 7
    - kapitel/daten-visualisieren/kapitel.md
    - kapitel/daten-visualisieren/pivot-tabellen.md
    # - kapitel/lineare-modelle/kapitel.md

  - references.qmd

format:
  html:
    theme: bootstrap
    toc: true
    html-math-method: katex

csl: _contrib/apa.csl